# **Assignments:1**

 Write a Python program to create a tensor of shape (3, 3) filled with random numbers between 0
and 1. Perform basic tensor operations including matrix addition, multiplication, and transpose.
Convert the resulting tensor into a NumPy array and then reshape it into a (1, 9) tensor.

In [3]:
import torch
import numpy as np

In [4]:
# 1: Create a 3x3 tensor with random numbers between 0 and 1.
tensor_a=torch.rand(3,3)
tensor_a

tensor([[0.0513, 0.4549, 0.1968],
        [0.7498, 0.9164, 0.7187],
        [0.7597, 0.6638, 0.6126]])

In [5]:
# 2: Create another 3x3 random tensor for operations.
tensor_b=torch.rand(3,3)
tensor_b

tensor([[0.6416, 0.0684, 0.9996],
        [0.7918, 0.2307, 0.7853],
        [0.2109, 0.5974, 0.1764]])

In [6]:
# 3: Perform matrix addition.
addition=tensor_a+tensor_b
addition

tensor([[0.6929, 0.5233, 1.1964],
        [1.5416, 1.1472, 1.5040],
        [0.9706, 1.2611, 0.7890]])

In [7]:
# 4: Perform matrix multiplication.
multiplication=torch.matmul(tensor_a,tensor_b)
multiplication

tensor([[0.4347, 0.2261, 0.4433],
        [1.3583, 0.6920, 1.5959],
        [1.1422, 0.5710, 1.3887]])

In [8]:
# OR
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2451, 0.8859, 0.9802],
        [0.6791, 0.8141, 0.5524],
        [0.4084, 0.7738, 0.7070]])

In [9]:
# 5: Transpose the multiplication result.
Transposed=multiplication.T
Transposed

tensor([[0.4347, 1.3583, 1.1422],
        [0.2261, 0.6920, 0.5710],
        [0.4433, 1.5959, 1.3887]])

In [14]:
print(type(Transposed))

<class 'torch.Tensor'>


In [10]:
# 6: Convert to NumPy array.
numpy_array = Transposed.numpy()
numpy_array

array([[0.43465143, 1.3582573 , 1.1421796 ],
       [0.22606803, 0.6920183 , 0.5710378 ],
       [0.44327554, 1.5959414 , 1.3887086 ]], dtype=float32)

In [11]:
print(type(numpy_array))

<class 'numpy.ndarray'>


In [12]:
# 7: Reshape into (1, 9).
reshaped_tensor = torch.tensor(numpy_array.reshape(1, 9))
reshaped_tensor

tensor([[0.4347, 1.3583, 1.1422, 0.2261, 0.6920, 0.5710, 0.4433, 1.5959, 1.3887]])

In [13]:
reshaped_tensor.shape

torch.Size([1, 9])