In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.8.0+cu126


# **Introduction to Tensors**
Creatintg Tensors

In [ ]:
# scalar
vector=torch.tensor([7,6])
vector

tensor([7, 6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[5,6],[7,8]])
matrix

tensor([[5, 6],
        [7, 8]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([5, 6])

In [ ]:
matrix[1]

tensor([7, 8])

In [ ]:
# Tensor
tensor=torch.tensor([[[1,2,3],[3,2,1],[4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 2, 1],
         [4, 5, 6]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

## Random Tensor

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0473, 0.5408, 0.0677, 0.3344],
        [0.0881, 0.8433, 0.8030, 0.0092],
        [0.6846, 0.1363, 0.7421, 0.6528]])

In [ ]:
torch.rand(3,3)

tensor([[0.9514, 0.4982, 0.2468],
        [0.4502, 0.4849, 0.0565],
        [0.8943, 0.6309, 0.5740]])

In [ ]:
zeros=torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Manipulation Tensors

# Addition
# Substraction
# Multiplication(element wise )
# Divison

In [ ]:
tensor=torch.tensor([1,2,3])


In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
tensor+10

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
# Matrix multiplication
# Inner dimesnsions must match:
# (3,2) @ (3,2)---- does not work
# (3,2) @ (2,3)---- does work
# (2,3) @ (3,2)---- does work

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.2577, 0.0626, 0.7136],
        [1.2134, 0.0597, 0.6539],
        [0.8050, 0.0397, 0.4403]])

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

In [ ]:
# create a tensor
x=torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
x.min()

tensor(0)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
# find the max
x.max()

tensor(90)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
# find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float).mean()

tensor(45.)

In [ ]:
# find the sum
torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

In [ ]:
# finding the positional min & max
x.argmin()


tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
# Reshaping
# lets create a tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.square()-removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])